### ISSUE TITLE
Installation of findr R package fails. 

### ISSUE THREAD

**Issue by sritchie73** [lingfeiwang/findr-R#3]
Running `devtools::install_github("lingfeiwang/findr-R", subdir="findr")` produces the following output in my R session: [findr_installation.log](https://github.com/lingfeiwang/findr-R/files/1529267/output.log).

The final few lines of output are:

```
libtool: link: gcc -g -O2 -o .libs/gsl-histogram gsl-histogram.o  ./.libs/libgsl.so cblas/.libs/libgslcblas.so -lm -Wl,-rpath -Wl,/usr/local/lib
creating gsl-config
creating gsl.pc
make[3]: Leaving directory `/tmp/RtmpMJJ3j7/devtoolsadbf7271c1b6/lingfeiwang-findr-R-213462a/findr/src/gsl'
make[2]: Leaving directory `/tmp/RtmpMJJ3j7/devtoolsadbf7271c1b6/lingfeiwang-findr-R-213462a/findr/src/gsl'
make[1]: Leaving directory `/tmp/RtmpMJJ3j7/devtoolsadbf7271c1b6/lingfeiwang-findr-R-213462a/findr/src/gsl'
cfextra="$(R CMD config --cppflags)"; \
	[ "$?" -eq "0" ] || exit 1; \
	make DIR_SRC_GSL=../gsl CFLAGS_EXTRA="$cfextra -DLIBEXTENSION_R=1" LDFLAGS_EXTRA="$LDFLAGS $(R CMD config --ldflags)" -C lib
make[1]: Entering directory `/tmp/RtmpMJJ3j7/devtoolsadbf7271c1b6/lingfeiwang-findr-R-213462a/findr/src/lib'
Testing gcc
make[1]: Leaving directory `/tmp/RtmpMJJ3j7/devtoolsadbf7271c1b6/lingfeiwang-findr-R-213462a/findr/src/lib'
Makefile:27: Makefile.flags: No such file or directory
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [Makefile.flags] Error 1
make: *** [all] Error 2
ERROR: compilation failed for package ‘findr’
``` 

I am trying to install findr on R 3.3.2 on Scientific Linux release 6.8 (64-bit) (based on the Red Hat distribution apparently). Installed on the cluster are gcc version 4.4.7, GNU Make 3.81, and GSL version 1.13. 

I have been able to install findr on another cluster with Ubuntu 16.04.3 (64-bit) using R 3.4.2 (gcc version 5.4.0, GNU make 4.1, GSL version 2.1), so this is potentially an operating system specific issue.

**Comment by lingfeiwang** [comment]
I tried to reproduce the issue on R 3.3.1, Scientific Linux 6.7 (64-bit), gcc 4.4.7, GNU make 3.81, but things worked out fine. Can you update devtools package if possible, try the test branch (giving more details, `devtools::install_github("lingfeiwang/findr-R", subdir="findr",ref='test')`), and also show the output of `sh --version` please?

**Comment by sritchie73** [comment]
Tried that and it still failed, here's the last few lines of the install process:

```
libtool: link: ranlib .libs/libgsl.a
libtool: link: rm -fr .libs/libgsl.lax .libs/libgsl.lax
libtool: link: ( cd ".libs" && rm -f "libgsl.la" && ln -s "../libgsl.la" "libgsl.la" )
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT gsl-randist.o -MD -MP -MF .deps/gsl-randist.Tpo -c -o gsl-randist.o gsl-randist.c
mv -f .deps/gsl-randist.Tpo .deps/gsl-randist.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o gsl-randist gsl-randist.o libgsl.la cblas/libgslcblas.la -lm 
libtool: link: gcc -g -O2 -o .libs/gsl-randist gsl-randist.o  ./.libs/libgsl.so cblas/.libs/libgslcblas.so -lm -Wl,-rpath -Wl,/usr/local/lib
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT gsl-histogram.o -MD -MP -MF .deps/gsl-histogram.Tpo -c -o gsl-histogram.o gsl-histogram.c
mv -f .deps/gsl-histogram.Tpo .deps/gsl-histogram.Po
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o gsl-histogram gsl-histogram.o libgsl.la cblas/libgslcblas.la -lm 
libtool: link: gcc -g -O2 -o .libs/gsl-histogram gsl-histogram.o  ./.libs/libgsl.so cblas/.libs/libgslcblas.so -lm -Wl,-rpath -Wl,/usr/local/lib
creating gsl-config
creating gsl.pc
make[3]: Leaving directory `/tmp/Rtmp33yxMN/devtools983d4c7823ef/lingfeiwang-findr-R-e447ddb/findr/src/gsl'
make[2]: Leaving directory `/tmp/Rtmp33yxMN/devtools983d4c7823ef/lingfeiwang-findr-R-e447ddb/findr/src/gsl'
make[1]: Leaving directory `/tmp/Rtmp33yxMN/devtools983d4c7823ef/lingfeiwang-findr-R-e447ddb/findr/src/gsl'
cfextra="$(R CMD config --cppflags)"; \
	[ "$?" -eq "0" ] || exit 1; \
	make DIR_SRC_GSL=../gsl CFLAGS_EXTRA="$cfextra -DLIBEXTENSION_R=1" LDFLAGS_EXTRA="$LDFLAGS $(R CMD config --ldflags)" -C lib
make[1]: Entering directory `/tmp/Rtmp33yxMN/devtools983d4c7823ef/lingfeiwang-findr-R-e447ddb/findr/src/lib'
Makefile:27: Makefile.flags: No such file or directory
Testing gcc
gcc --version &> /dev/null || ( echo "GCC not found. Please download the latest GCC or specify its location in CC variable in Makefile."; exit 1; )
gver=$(gcc --version) ; \
	t1=$(echo "$gver" | grep -io gcc); \
	if ! [ -n "$t1" ]; then echo "Invalid GCC version. Please download the latest GCC."; exit 1; fi
cflags=" WARNING: ignoring environment value of R_HOME
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [Makefile.flags] Error 1
make[1]: Leaving directory `/tmp/Rtmp33yxMN/devtools983d4c7823ef/lingfeiwang-findr-R-e447ddb/findr/src/lib'
make: *** [all] Error 2
ERROR: compilation failed for package ‘findr’
* removing ‘/home/sr827/R/x86_64-pc-linux-gnu-library/3.3/findr’
* restoring previous ‘/home/sr827/R/x86_64-pc-linux-gnu-library/3.3/findr’
Installation failed: Command failed (1)
```

`sh --version` returns `GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)`

Running `system("sh --version")` in the R session is returning the same thing (same with the other software dependencies), and `which sh` and `system("which sh")` are reporting `/bin/sh`

**Comment by sritchie73** [comment]
Ok just found they've added R version 3.4.2 on the cluster, and I was able to successfully install `findr` using `devtools::install_github("lingfeiwang/findr-R", subdir="findr",ref='test')`.

**Comment by lingfeiwang** [comment]
That seems to be caused by R printing unformatted warning messages into cflags and ldflags when R_HOME environment is set. The new test branch should account for the misbehaviour. Can you give it a try in your R 3.3.2?

**Comment by sritchie73** [comment]
I've uploaded the messages I get when trying to install from the new test brach on R/3.3.2 on the cluster: [output.log](https://github.com/lingfeiwang/findr-R/files/1537292/output.log)

It seems like its now failing to link properly to GSL.

**Comment by lingfeiwang** [comment]
Thank you for reporting and testing the issue.

That is failing to find the library 'icuuc'. It's most probably due to incomplete installation of R or R's bug, because R tells the findr library to include this icuuc library but doesn't provide it in the designated folder. There's nothing we can do about it.

However, the R_HOME environment issue has been accounted for in this version. The master branch has been updated accordingly.
