### ISSUE TITLE
findr-R fails to install

### ISSUE THREAD

**Issue by Wanff** [lingfeiwang/findr-R#7]
Hi Lingfei, 

Thank you for creating this package. I ran into this error when downloading the package with `R CMD INSTALL findr`
<img width="619" alt="Screen Shot 2021-01-07 at 10 49 57 PM" src="https://user-images.githubusercontent.com/50050060/103972285-abf75c00-513a-11eb-9bb3-595d2d676fff.png">

Specs:
MacOS 10.15.6
GNUMake 3.81
gcc-10 (Homebrew GCC 10.2.0) 10.2.0
GSL  2.6
R Version 4.0

Thank you for your help.
Kevin

**Comment by lingfeiwang** [comment]
Hi Kevin,

That seems to be some internal inconsistency between gcc and openmp. Can you try commit 3188744908b0e97f6ccf30b5cdb08096d1c989a9?

**Comment by Wanff** [comment]
Hi Lingfei, 

Thank you for your prompt response. I downloaded the commit and ran `R CMD INSTALL findr` again. I got the following error message:
```Invalid GCC version. Please download the latest GCC.
Makefile:26: Makefile.flags: No such file or directory
make[1]: *** [Makefile:152: Makefile.flags] Error 1
make[1]: Leaving directory '/Users/kevinwang/Desktop/code/myopia/new-findr-R/findr/src/lib'
make: *** [Makefile:7: all] Error 2
ERROR: compilation failed for package ‘findr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/findr’
```

Then, I modified the Makefile in src/lib to gcc-10 (which I did in the original error) and got the following error message:
```Testing test method
Linking with default flags failed.
Makefile:26: Makefile.flags: No such file or directory
make[1]: *** [Makefile:153: Makefile.flags] Error 1
make[1]: Leaving directory '/Users/kevinwang/Desktop/code/myopia/new-findr-R/findr/src/lib'
make: *** [Makefile:7: all] Error 2
ERROR: compilation failed for package ‘findr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/findr’ 
```

Again, thank you so much for your help,
Kevin

**Comment by lingfeiwang** [comment]
This error seems related to an earlier error. Could you rerun `R CMD INSTALL findr` from a new folder and send the full output message?

**Comment by Wanff** [comment]
Yes, sorry, here is the full output log from running` R CMD INSTALL findr` from a new folder: [output.log](https://github.com/lingfeiwang/findr-R/files/5803237/output.log)

**Comment by lingfeiwang** [comment]
It appears that you are not using gcc 10. More likely it's clang. Can you retry in a new folder with gcc instead?

**Comment by Wanff** [comment]
Yep, pointing to gcc-10 in the Makefile and running in a new folder results in the following error: [output.log](https://github.com/lingfeiwang/findr-R/files/5803399/output.log)

**Comment by lingfeiwang** [comment]
It seems due to malfunctioning gcc linking. Can you try commit 7a2e388abee88d8eee0d25e92a719d2bd6771f26 that gives more detailed log for what is wrong?

**Comment by Wanff** [comment]
yes, that commit results in the following log: [output.log](https://github.com/lingfeiwang/findr-R/files/5838911/output.log)

Thank you, 
Kevin

**Comment by lingfeiwang** [comment]
This should be a problem of your building environment. The error is `ld: library not found for -lpcre2-8`. I googled the error and one possible solution is https://github.com/ponylang/ponyc/issues/226. If that doesn't work, you can try the binary or python interfaces.

**Comment by Wanff** [comment]
I was able to compile and download R from the most recent commit you sent (but not previous ones). Thank you!
